### ISSUE TITLE
Fetch vote average

### ISSUE THREAD

**Issue by samagragupta** [NJACKWinterOfCode/Moviepedia#4]
fetch vote average field in the movie detail section.

**Comment by shreyateeza** [comment]
@samagragupta Can you please guide me through the issue? I would like to work on this.

**Comment by samagragupta** [comment]
@shreyateeza This vote average is not fetching properly.
![Capture](https://user-images.githubusercontent.com/32234926/69918185-eea92800-1494-11ea-9266-dfc5c2461db5.JPG)

**Comment by dev-sankhadip** [comment]
Is there anyone working on this issue? I am willing to do it.Issue has been already sorted out by me just i need pull request. Can i sir?

**Comment by samagragupta** [comment]
@dev-sankhadip Go ahead 🚀

**Comment by dev-sankhadip** [comment]
![Screenshot from 2019-12-04 18-22-46](https://user-images.githubusercontent.com/50552816/70144198-6fe60200-16c3-11ea-8a66-a935db9ab975.png)

**Comment by dev-sankhadip** [comment]
I just made pull request, can you please check it out and accept pull request?
